### ISSUE TITLE
prediction problem

### ISSUE THREAD

**Issue by vcvishal** [xiongzihua/pytorch-YOLO-v1#25]
when i tried to predict this error occurred 

load model...
predicting...
predict.py:143: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = Variable(img[None,:,:,:],volatile=True)
D:\miniconda\lib\site-packages\torch\nn\functional.py:1332: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "predict.py", line 174, in <module>
    result = predict_gpu(model,image_name)
  File "predict.py", line 148, in predict_gpu
    boxes,cls_indexs,probs =  decoder(pred)
  File "predict.py", line 89, in decoder
    cls_indexs = torch.cat(cls_indexs,0) #(n,)
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

please guide 
thank you

**Comment by ChengJianjia** [comment]
Hi，I met the same problem，have you solve it？

**Comment by yahsiuhsieh** [comment]
@JianJiaCheng Try to use `torch.stack()` instead.

**Comment by TanMeng0** [comment]
add   cls_indexs = [item.unsqueeze(0) for item in cls_indexs] 
before    cls_indexs = torch.cat(cls_indexs,0)

**Comment by TanMeng0** [comment]
@vcvishal @JianJiaCheng 
add：   cls_indexs = [item.unsqueeze(0) for item in cls_indexs] 
before ：   cls_indexs = torch.cat(cls_indexs,0)
