### ISSUE TITLE
eval error

### ISSUE THREAD

**Issue by vcvishal** [xiongzihua/pytorch-YOLO-v1#26]
C:\Users\vcvis\Desktop\pytorch-YOLO-v1-master>python eval_voc.py
---prepare target---
---start test---
  0%|                                                                                         | 0/4951 [00:00<?, ?it/s]C:\Users\vcvis\Desktop\pytorch-YOLO-v1-master\predict.py:143: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = Variable(img[None,:,:,:],volatile=True)
D:\miniconda\lib\site-packages\torch\nn\functional.py:1332: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
  0%|                                                                                 | 4/4951 [00:01<55:21,  1.49it/s]
Traceback (most recent call last):
  File "eval_voc.py", line 186, in <module>
    result = predict_gpu(model,image_path,root_path='./VOCdevkit/VOC2012/JPEGImages/') #result[[left_up,right_bottom,class_name,image_path],]
  File "C:\Users\vcvis\Desktop\pytorch-YOLO-v1-master\predict.py", line 148, in predict_gpu
    boxes,cls_indexs,probs =  decoder(pred)
  File "C:\Users\vcvis\Desktop\pytorch-YOLO-v1-master\predict.py", line 90, in decoder
    keep = nms(boxes,probs)
  File "C:\Users\vcvis\Desktop\pytorch-YOLO-v1-master\predict.py", line 107, in nms
    i = order[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

please help

**Comment by vcvishal** [comment]
I used
i = order.item()

but it doesn't work

**Comment by yahsiuhsieh** [comment]
Move this line of code `if order.numel() == 1: break` in front of `i = order.item()`.

**Comment by leiqing110** [comment]
> Move this line of code `if order.numel() == 1: break` in front of `i = order.item()`.

i do this according to your reply ,but it does not work. would you tell me more info about it ？

**Comment by leiqing110** [comment]
你好 请问你这个问题解决了吗 我也同样的问题

**Comment by thaodod** [comment]
order sometimes is list, sometime only 1 element. (it's order!), so when only 1 element --> use .item(), when it's a list. use .list()[0]

**Comment by buaacarzp** [comment]
hello,everybody, I have solved this problem. It just caused by the version of pytorch. most of all use the pytorch>=0.4,but this version of torch is 0.3 or lower.
here is the solution of nms:
```
def nms(bboxes,scores,threshold=0.5):
    '''
    bboxes(tensor) [N,4]
    scores(tensor) [N,]
    '''
    x1 = bboxes[:,0]
    y1 = bboxes[:,1]
    x2 = bboxes[:,2]
    y2 = bboxes[:,3]
    areas = (x2-x1) * (y2-y1)

    _,order = scores.sort(0,descending=True)
    # print("order1:",order)
    keep = []
    while order.numel() > 0:
        if order.numel()>1:
            i = order.tolist()[0]   
            keep.append(i)
        else:
            keep.append(order.item())
            break

        xx1 = x1[order[1:]].clamp(min=x1[i])
        yy1 = y1[order[1:]].clamp(min=y1[i])
        xx2 = x2[order[1:]].clamp(max=x2[i])
        yy2 = y2[order[1:]].clamp(max=y2[i])

        w = (xx2-xx1).clamp(min=0)
        h = (yy2-yy1).clamp(min=0)
        inter = w*h

        ovr = inter / (areas[i] + areas[order[1:]] - inter)
        ids = (ovr<=threshold).nonzero().squeeze()
        if ids.numel() == 0:
            break
        order = order[ids+1] 
    return torch.LongTensor(keep)

```_
